#!/bin/bash

# prefs.js hash: {{include (joinPath .chezmoi.homeDir ".mozilla/firefox/brauni/prefs.js") | sha256sum }}
PREFS={{- joinPath .chezmoi.homeDir ".mozilla/firefox/brauni/prefs.js" }}
echo $PREFS
#sed -i 's/user_pref("toolkit.legacyUserProfileCustomizations.stylesheets", false);/user_pref("toolkit.legacyUserProfileCustomizations.stylesheets", true);/g' $PREFS
