#! /bin/sh

sxhkd &

# run the xrandr command if an external monitor is connected to the
# laptop.  This must be executed before the polybar command, so that
# polybar can set the two separate bars properly.
#if [ -x /home/brauni/.config/bspwm/dual_monitor ];then
#    sh /home/brauni/.config/bspwm/dual_monitor
#fi



#bspc monitor DVI-D-0 -d I II III IV 
#bspc monitor HDMI-0 -d V VI VII VIII

i=0
n=`bspc query -M | wc -l`  # count number of lines in bspwm's monitor list
per=$(( 4 / n ))          # number of desktops per monitor
for monitor in `bspc query -M`; do
    bspc monitor $monitor -d `seq $i $(( i + per - 1 ))` 
    # seq is end-inclusive; `seq 1 $((1+2))` returns "1 2 3"
    i=$(( i + per ))
done

bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true

bspc config border_width        1
bspc config window_gap          10

bspc config top_padding 33
bspc config left_padding 1
bspc config right_padding 1
bspc config bottom_padding 1

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      false
bspc config focus_follows_pointer true

bspc config pointer_modifier mod1
bspc config pointer_action3 resize_side
bspc config pointer_action3 resize_corner
bspc config pointer_action1 move

bspc rule -a Docky layer=above manage=on border=off focus=off locked=on
bspc rule -a xfce4-notes floating=on

